# Generated by Django 4.1.7 on 2023-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoweb', '0002_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shoe_size',
            field=models.CharField(choices=[('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10'), ('eleven', '11'), ('twelve', '12'), ('thirteen', '13'), ('fourteen', '14')], max_length=15, null=True),
        ),
    ]
